### PR TITLE
Fix for GitHub rate limiting, fix timezone variable error, delete default config.php, include config.php first

### PR DESCRIPTION
**Pull request by Unimatrix0**

### CODE REVIEW

**Comment by wjbeckett** [comment]
Nice PR. 
Will need to keep the config.php.

I've tried to remove it however @seanvree would like it remain so the user has a config working 'at first pull'

**Comment by seanvree** [comment]
@wjbeckett @Unimatrix0  thanks for contributing.  

Correct, i'd like to keep the initial config.php

**Comment by jonfinley** [comment]
Don't reference timezone from config if empty < no need, we already check for that.
Add github OAuth2 token field to sample config < I'm good with this
Delete config.php < we would like to keep an initial config.php for first work, @wjbeckett @seanvree maybe we can write somethign that uses the sample if no config.php availalbe, be dangerous for any config changes..?
include config.php first < does it matter? what dos this change?
use GitHub OAuth token if set < have you tested that this works? @Unimatrix0 

I am unabable to test some of the changes at the moment.

**Comment by Unimatrix0** [comment]
@jonfinley 
- Don't reference timezone from config if empty < no need, we already check for that.
  - No we don't. Without this change, I get an error:
`2017/10/26 21:01:21 [error] 29843#29843: *234260 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: timezone in /opt/monitorr/assets/php/timestamp.php on line 4" while reading response header from upstream, client: [REDACTED], server: , request: "POST /monitor/assets/php/timestamp.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "[REDACTED]", referrer: "https://[REDACTED]/monitor/"`

- Delete config.php < we would like to keep an initial config.php for first work, @wjbeckett @seanvree maybe we can write somethign that uses the sample if no config.php availalbe, be dangerous for any config changes..?
  - Ideally, if config.php doesn't exist, it should be automatically created from config.php.sample
- include config.php first < does it matter? what does this change?
  - it's in the commit comments
- use GitHub OAuth token if set < have you tested that this works? @Unimatrix0
  - Yep, works great.

**Comment by jonfinley** [comment]
Interesting, I havent had that issue even in my testing. what flavor of linux are you running? I removed the UTC from my config and did not throw any errors.

**Comment by wjbeckett** [comment]
@jonfinley That's correct. the Gitinfo function is no longer in use. This function will be removed shortly.

**Comment by jonfinley** [comment]
'Merged' https://github.com/Monitorr/Monitorr/commit/5ac8a285f1487e68e2d92de4e7325793e5942deb

updated config.php with new options. Not removing until we have an auto-populate function built in. Sadly, this does mean overwrites. @wjbeckett @seanvree while we build the settings page lets look at a way we can populate if there is no config.php file.
if no file exists include Plex, Sonarr, Radarr, etc.

**Pull request closed without merging**
