### PR TITLE
Update to alpine 3.7

### PR DESCRIPTION
**Pull request by aptalca**

### CODE REVIEW

**Comment by seanvree** [comment]
@jonfinley  @si0972  You guys see an issue with this?

**Comment by si0972** [comment]
I don't, I trust the lsio team with the commit.

31. mai 2018 kl. 14:10 skrev Sean Vreeland <notifications@github.com<mailto:notifications@github.com>>:


@jonfinley<https://github.com/jonfinley> @si0972<https://github.com/si0972> You guys see an issue with this?

**Comment by seanvree** [comment]
Will merge when the new version is out in the next few days.

**Comment by aptalca** [comment]
yeah, we switched all our downstream images to use 3.7 a little while back. It is well tested now

**Comment by aptalca** [comment]
I just happened to notice that monitorr uses our baseimage when I was testing the new reverse proxy confs for it: https://github.com/linuxserver/docker-letsencrypt/blob/master/root/defaults/proxy-confs/monitorr.subfolder.conf.sample
https://github.com/linuxserver/docker-letsencrypt/blob/master/root/defaults/proxy-confs/monitorr.subdomain.conf.sample

**Comment by seanvree** [comment]
manually merged with a hotfix.  thanks @aptalca !!!

https://github.com/Monitorr/Monitorr/commit/caa7cb43007d687ac24904e31b06a1935ead7e1a

**Pull request closed without merging**
