### PR TITLE
Fix ram percentage for window based machines

### PR DESCRIPTION
**Pull request by lucidonlinenet**
I updated the functions.php to correctly show ram percentage for window based machines

### CODE REVIEW

**Comment by lucidonlinenet** [comment]
Yes, it's that issue, sorry didn't see it otherwise I would have referenced it.

**Comment by seanvree** [comment]
@lucidonlinenet  no problem, what OS did you test this on? where you seeing this issue as well?

**Comment by lucidonlinenet** [comment]
Tested on windows 10, 7 and ubuntu 17.10 but may be worth a test on other OS. I was getting the same issue on windows as #67.

**Comment by seanvree** [comment]
@lucidonlinenet  Cool, let me give this a go and test. Really appreciate you contributing.

**Comment by seanvree** [comment]
Pushed to TEST branch for testing

**Pull request merged**
